# Generated by Django 4.1.4 on 2023-03-02 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Order Received', 'Order Received'), ('Order Processing', 'Order Processing'), ('Order Completed', 'Order Completed'), ('Order Canceled', 'Order Canceled'), ('Order Deleted', 'Order Deleted'), ('On The Way', 'On The Way')], max_length=100),
        ),
    ]
